"""Create main tables.

Revision ID: 33a7a0473f46
Revises: 
Create Date: 2024-05-07 11:20:07.251060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a7a0473f46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boughtinproductasapartof',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_date'), 'feedback', ['date'], unique=False)
    op.create_table('question',
    sa.Column('package', sa.String(length=256), nullable=True),
    sa.Column('tour', sa.String(length=256), nullable=True),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('question_type', sa.Enum('Б', 'ДБ', 'И', 'Л', 'Ч', 'ЧБ', 'ЧД', 'Э', 'Я', name='questiontype'), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('pass_criteria', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('condemned', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_condemned'), 'question', ['condemned'], unique=False)
    op.create_index(op.f('ix_question_is_published'), 'question', ['is_published'], unique=False)
    op.create_index(op.f('ix_question_question_type'), 'question', ['question_type'], unique=False)
    op.create_table('boughtinproduct',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('a_part_of_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.SmallInteger(), nullable=True),
    sa.Column('product_type', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['a_part_of_id'], ['boughtinproductasapartof.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boughtinproductlink',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('link_short_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['boughtinproduct.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boughtinproductlink')
    op.drop_table('boughtinproduct')
    op.drop_index(op.f('ix_question_question_type'), table_name='question')
    op.drop_index(op.f('ix_question_is_published'), table_name='question')
    op.drop_index(op.f('ix_question_condemned'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_feedback_date'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('boughtinproductasapartof')
    # ### end Alembic commands ###
